server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-ct196dggph6c73bgpu00-a.oregon-postgres.render.com:5432/filmes_0lra
        username: filmes_0lra_user
        password: 1Ty28XYeNixdfvArk3QUMyzg7Pbsd2DL
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa: 
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres

